name: Build and Push Shield Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_OUTPUT"

      - name: Log in to ghcr
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build .\
            -t ghcr.io/${{ github.repository_owner }}/dc-shield:${{ steps.extract_branch.outputs.branch }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/dc-shield:${{ steps.extract_branch.outputs.branch }}
